# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala, java

scala:
   - 2.11.8

jdk:
  - oraclejdk8

script: cd rest-server && sbt ++$TRAVIS_SCALA_VERSION test && cd ../java-sdk && mvn clean deploy

branches:
  only:
    - master
    - develop

notifications:
  email:
    recipients:
      - semen@actionml.com