# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala
scala:
   - 2.11.8
script: cd rest-server && sbt ++$TRAVIS_SCALA_VERSION test
branches:
  only:
    - master
    - develop
notifications:
  email:
    recipients:
      - semen@actionml.com
jdk:
  - oraclejdk8