version: '3'

services:

  mongo:
    image: mongo:3.2
    ports:
      - '27017:27017'
    logging:
      driver: none

  router:
    build: ./rest-server
    ports:
      - '9090:9090'
    environment:
      MONGO_HOST: "mongo"
      REST_SERVER_HOST: "0.0.0.0"
      REST_SERVER_PORT: "9090"
    depends_on:
      - mongo
    volumes:
      - ./data:/app/data

#  java_client:
#    build: ./java-sdk/example
#
#    depends_on:
#      - router
