# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala
scala:
   - 2.11.8
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - semen@actionml.com
jdk:
  - oraclejdk8